export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const AUTHENTICATE_USER_STATE = 'AUTHENTICATE_USER_STATE';

export const REGISTER_HSID_SUCCESS = 'REGISTER_HSID_SUCCESS';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS';
export const LOGGING_IN = 'LOGGING_IN';




/* Load all campaigns */

export const LOAD_CAMPAIGNS_LOADING = 'LOAD_CAMPAIGNS_LOADING';
export const LOAD_CAMPAIGNS_SUCCESS = 'LOAD_CAMPAIGNS_SUCCESS';
export const LOAD_CAMPAIGNS_FAILED = 'LOAD_CAMPAIGNS_FAILED';

/* Load single campaign */

export const LOAD_CAMPAIGN_LOADING = 'LOAD_CAMPAIGN_LOADING';
export const LOAD_CAMPAIGN_SUCCESS = 'LOAD_CAMPAIGN_SUCCESS';
export const LOAD_CAMPAIGN_FAILED = 'LOAD_CAMPAIGN_FAILED';

/* Update single campaign */

export const UPDATE_CAMPAIGN_SAVING = 'UPDATE_CAMPAIGN_SAVING';
export const UPDATE_CAMPAIGN_SUCCESS = 'UPDATE_CAMPAIGN_SUCCESS';
export const UPDATE_CAMPAIGN_FAILED = 'UPDATE_CAMPAIGN_FAILED';

/* Get Bit.ly link */ 

export const GET_SHORT_URL_LOADING = 'GET_SHORT_URL_LOADING';
export const GET_SHORT_URL_SUCCESS = 'GET_SHORT_URL_SUCCESS';
export const GET_SHORT_URL_FAILED = 'GET_SHORT_URL_FAILED';
export const CLEAR_SHORT_URL = 'CLEAR_SHORT_URL';







export const CREATE_CAMPAIGN_SUCCESS = 'CREATE_CAMPAIGN_SUCCESS';
export const SAVE_CAMPAIGN_SUCCESS = 'SAVE_CAMPAIGN_SUCCESS';
